import Head from 'next/head';
import { Inter } from '@next/font/google';
import sites from '../data/sites-supported';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>TL;DR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-[1fr_2fr_1fr]">
          <div></div>
          <div>
            <h1 className="text-6xl font-bold text-center mt-10 mb-5">TL;DR</h1>
            <p className="text-center mb-10">Enter the URL of an article to get a short summary</p>
            <div className="grid grid-cols-[5fr_1fr] mb-2 gap-5">
              <input
                type="text"
                name="inputUrl"
                id="inputUrl"
                className="border-solid border-slate-400 border rounded-md p-2 w-full height-full"
              />
              <button className="bg-indigo-500 text-white rounded-md">Summarize</button>
            </div>
            <p className="text-slate-500 text-sm">
              Supported sites:{' '}
              {sites.map((site) => {
                return (
                  <>
                    <a
                      href={site.fullurl}
                      key={site.hostname}
                      className="underline text-blue-600"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {site.name}
                    </a>
                    {sites.findIndex((s) => s.name === site.name) !== sites.length - 1 ? ', ' : ''}
                  </>
                );
              })}
            </p>
          </div>
          <div></div>
        </div>
      </main>
    </>
  );
}
